### ISSUE TITLE
Update in QuickStartGuide.txt

### ISSUE THREAD

**Issue by vietvhnguyen** [DigitalSpadArraySimulator/DigitalSpadArraySimulator#2]
Hello 
I am Viet.
I am an intern at 3IT. 
I currently use the DSAS module for my geant4 simulation.

In the QuickStartGuide.txt, there is an instruction about the position unit of the root data.
The current unit in the guide is um, but I found in the root_event_importer.cc, there is a line to convert the position unit from mm to um.
I also tested with 2 identical data sets, the difference is just the position unit, one is mm and the other is um. 
DSAS output for the "mm" set has the avalanche, while the output for the "um" set does not. 

Maybe there should be an update in the guide for future users.
Thank you.

**Comment by lemwill** [comment]
Hi Viet, Thanks for the update. I believe you can do a pull request to modify the user guide. 

Thank you.
